// xsamplefe_plugin.cpp -- Stata plugin behind `xsamplefe`: panel / fixed-effect
// aware random sampling that feeds reghdfe/xhdfe (absorb(), group(),
// individual()) while reproducing Stata's `sample` and Weesie's `sample2`
// semantics for the simple cases.
//
// Design contract (see xsamplefe.sthlp):
//   * Observation-level sampling (no unit) draws the n_g observations with the
//     smallest (u1, u2, ...) keys inside every stratum g, where the u_c columns
//     are uniforms generated by the ado with runiform(); this makes the drawn
//     rows bit-identical to `sample` under the same seed and data order.
//   * Unit-level sampling (unit(), absorb(), group()) draws whole units. The
//     r-th smallest unit value inside the sampling frame receives the r-th
//     uniform draw, so the drawn set depends only on the seed and the set of
//     unit values, never on the physical row order of the data.
//   * Every parallel phase is deterministic: results are invariant to the
//     OpenMP team size (sorts are rank-based, selection is by total order).
//   * Counts and sizes are kept in 64-bit integers.
//
// varlist layout handed over by the ado (all numeric):
//   [1]              touse  (1 = inside if/in and non-missing keys)
//   [..]             unit   (if has_unit)
//   [..]             by strata columns (nby)
//   [..]             time   (if has_time)
//   [..]             mob    (if has_mob)
//   [..]             group  (if has_group; block of inseparable rows)
//   [..]             u_1 .. u_nu uniform key columns (nu >= 0)
//   [last]           out    (byte/double target: 1 = retained, 0 = dropped)
#include "stplugin.h"

#include <algorithm>
#include <cerrno>
#include <cctype>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#ifdef _OPENMP
#include <omp.h>
#endif

// Parallel sort when libstdc++ parallel mode is available (GCC host compiler
// with OpenMP). Every use below is a rank assignment whose output is
// invariant to how equal keys are ordered, so results are bit-identical to
// the serial std::sort fallback.
#if defined(__GNUC__) && defined(_OPENMP) && __has_include(<parallel/algorithm>)
#include <parallel/algorithm>
#define XSF_PARALLEL_SORT(first, last, cmp) __gnu_parallel::sort((first), (last), (cmp))
#else
#define XSF_PARALLEL_SORT(first, last, cmp) std::sort((first), (last), (cmp))
#endif

namespace {

constexpr const char* kPrefix = "xsamplefe plugin: ";

[[noreturn]] void fail(const std::string& msg) {
    throw std::runtime_error(std::string(kPrefix) + msg);
}

std::string to_lower(std::string s) {
    std::transform(s.begin(), s.end(), s.begin(), [](unsigned char c) {
        return static_cast<char>(std::tolower(c));
    });
    return s;
}

std::string trim(const std::string& s) {
    std::size_t b = 0;
    std::size_t e = s.size();
    while (b < e && std::isspace(static_cast<unsigned char>(s[b]))) ++b;
    while (e > b && std::isspace(static_cast<unsigned char>(s[e - 1]))) --e;
    return s.substr(b, e - b);
}

// ---------------------------------------------------------------------------
// Argument parsing: a single packed "cfg=key=value;key=value;..." string.
// ---------------------------------------------------------------------------
struct ParsedArgs {
    std::unordered_map<std::string, std::string> kv;

    explicit ParsedArgs(int argc, char* argv[]) {
        auto parse_item = [&](const std::string& item) {
            if (item.empty()) return;
            const std::size_t eq = item.find('=');
            if (eq == std::string::npos || eq == 0) {
                fail("invalid argument (expected key=value): " + item);
            }
            kv.emplace(item.substr(0, eq), item.substr(eq + 1));
        };
        auto parse_packed = [&](std::string packed) {
            if (packed.rfind("cfg=", 0) == 0) packed.erase(0, 4);
            std::string buf;
            for (char c : packed) {
                if (c == ';') {
                    parse_item(buf);
                    buf.clear();
                } else {
                    buf.push_back(c);
                }
            }
            parse_item(buf);
        };
        if (argc == 1) {
            const std::string only = argv[0] ? argv[0] : "";
            if (only.find(';') != std::string::npos || only.rfind("cfg=", 0) == 0) {
                parse_packed(only);
                return;
            }
        }
        for (int i = 0; i < argc; ++i) {
            parse_item(argv[i] ? argv[i] : "");
        }
    }

    const std::string& required(const char* key) const {
        auto it = kv.find(key);
        if (it == kv.end()) fail(std::string("missing required argument: ") + key);
        return it->second;
    }
    std::optional<std::string> optional(const char* key) const {
        auto it = kv.find(key);
        if (it == kv.end()) return std::nullopt;
        return it->second;
    }
};

bool parse_bool(const std::string& raw, const char* what) {
    const std::string s = to_lower(trim(raw));
    if (s == "1" || s == "true" || s == "yes") return true;
    if (s == "0" || s == "false" || s == "no" || s.empty()) return false;
    fail(std::string("invalid boolean for ") + what + ": " + raw);
}

long long parse_ll(const std::string& raw_in, const char* what) {
    const std::string raw = trim(raw_in);
    char* end = nullptr;
    errno = 0;
    const long long v = std::strtoll(raw.c_str(), &end, 10);
    if (errno != 0 || end == raw.c_str() || *end != '\0') {
        fail(std::string("invalid integer for ") + what + ": " + raw);
    }
    return v;
}

int parse_int(const std::string& raw, const char* what) {
    const long long v = parse_ll(raw, what);
    if (v < std::numeric_limits<int>::min() || v > std::numeric_limits<int>::max()) {
        fail(std::string("integer out of range for ") + what + ": " + raw);
    }
    return static_cast<int>(v);
}

double parse_double(const std::string& raw_in, const char* what) {
    const std::string raw = trim(raw_in);
    char* end = nullptr;
    errno = 0;
    const double v = std::strtod(raw.c_str(), &end);
    if (errno != 0 || end == raw.c_str() || *end != '\0') {
        fail(std::string("invalid numeric for ") + what + ": " + raw);
    }
    return v;
}

// ---------------------------------------------------------------------------
// OpenMP contract (same as the xhdfe/xfepout plugins): an explicit positive
// request creates a real team of that size up to the runtime capacity; the
// caller's ICVs are restored afterwards. Automatic mode leaves the runtime
// default untouched.
// ---------------------------------------------------------------------------
class ScopedThreadRequest {
public:
    explicit ScopedThreadRequest(int requested) {
#ifdef _OPENMP
        if (requested <= 0) return;
        if (requested > 1 && omp_in_parallel()) {
            fail("explicit numthreads() > 1 cannot be guaranteed inside an active OpenMP region");
        }
        previous_dynamic_ = omp_get_dynamic();
        previous_threads_ = omp_get_max_threads();
        const int capacity = std::max(1, std::min(omp_get_num_procs(), omp_get_thread_limit()));
        omp_set_dynamic(0);
        omp_set_num_threads(std::max(1, std::min(requested, capacity)));
        active_ = true;
#else
        (void)requested;
#endif
    }
    ~ScopedThreadRequest() {
#ifdef _OPENMP
        if (active_) {
            omp_set_num_threads(previous_threads_);
            omp_set_dynamic(previous_dynamic_);
        }
#endif
    }
    ScopedThreadRequest(const ScopedThreadRequest&) = delete;
    ScopedThreadRequest& operator=(const ScopedThreadRequest&) = delete;

private:
#ifdef _OPENMP
    bool active_ = false;
    int previous_dynamic_ = 0;
    int previous_threads_ = 1;
#endif
};

struct ThreadStats {
    int max_team = 1;
};

// Call from inside a parallel region: the master thread records the team size
// actually formed (the reported threads_used is the maximum observed).
inline void observe_team(ThreadStats& ts) {
#ifdef _OPENMP
    if (omp_get_thread_num() == 0) {
        ts.max_team = std::max(ts.max_team, omp_get_num_threads());
    }
#else
    (void)ts;
#endif
}

inline int effective_threads() {
#ifdef _OPENMP
    return std::max(1, omp_get_max_threads());
#else
    return 1;
#endif
}

// ---------------------------------------------------------------------------
// Configuration.
// ---------------------------------------------------------------------------
enum class FrameRule { Strict, Any, All };
enum class GroupRule { Any, All };
enum class ReconRule { Gain, Key };

struct Config {
    bool is_count = false;
    double pct = 0.0;
    long long count = 0;
    bool has_unit = false;
    int nby = 0;
    bool has_time = false;
    bool has_mob = false;
    bool has_group = false;
    int nu = 0;
    FrameRule frame_rule = FrameRule::Strict;
    GroupRule group_rule = GroupRule::Any;
    bool balanced = false;
    long long minobs = -1, maxobs = -1;
    long long minperiods = -1, maxperiods = -1;
    long long minmob = -1, maxmob = -1;
    bool has_rate_movers = false, has_rate_stayers = false;
    double rate_movers = 0.0, rate_stayers = 0.0;
    bool mobstrata = false;
    bool connectivity = false;
    bool reconnect = false;
    ReconRule recon_rule = ReconRule::Gain;
    double recon_target = -1.0;  // percent; < 0 = the frame's largest-component share
    bool connected = false;
    int num_threads = 0;
    bool verbose = false;
    std::string s_prefix;
};

FrameRule parse_frame_rule(const std::string& raw) {
    const std::string s = to_lower(raw);
    if (s == "strict" || s.empty()) return FrameRule::Strict;
    if (s == "any") return FrameRule::Any;
    if (s == "all") return FrameRule::All;
    fail("invalid frame_rule: " + raw);
}

ReconRule parse_recon_rule(const std::string& raw) {
    const std::string s = to_lower(raw);
    if (s == "gain" || s.empty()) return ReconRule::Gain;
    if (s == "key") return ReconRule::Key;
    fail("invalid recon_rule: " + raw);
}

GroupRule parse_group_rule(const std::string& raw) {
    const std::string s = to_lower(raw);
    if (s == "any" || s.empty()) return GroupRule::Any;
    if (s == "all") return GroupRule::All;
    fail("invalid group_rule: " + raw);
}

Config parse_config(const ParsedArgs& a) {
    Config c;
    c.is_count = parse_bool(a.required("is_count"), "is_count");
    if (c.is_count) {
        c.count = parse_ll(a.required("count"), "count");
        if (c.count < 0) fail("count must be nonnegative");
    } else {
        c.pct = parse_double(a.required("pct"), "pct");
        if (!(c.pct >= 0.0 && c.pct <= 100.0)) fail("pct must be between 0 and 100");
    }
    c.has_unit = parse_bool(a.required("has_unit"), "has_unit");
    c.nby = parse_int(a.required("nby"), "nby");
    c.has_time = parse_bool(a.required("has_time"), "has_time");
    c.has_mob = parse_bool(a.required("has_mob"), "has_mob");
    c.has_group = parse_bool(a.required("has_group"), "has_group");
    c.nu = parse_int(a.required("nu"), "nu");
    if (c.nby < 0 || c.nu < 0) fail("invalid dimension arguments");
    if (auto v = a.optional("frame_rule")) c.frame_rule = parse_frame_rule(*v);
    if (auto v = a.optional("group_rule")) c.group_rule = parse_group_rule(*v);
    if (auto v = a.optional("balanced")) c.balanced = parse_bool(*v, "balanced");
    if (auto v = a.optional("minobs")) c.minobs = parse_ll(*v, "minobs");
    if (auto v = a.optional("maxobs")) c.maxobs = parse_ll(*v, "maxobs");
    if (auto v = a.optional("minperiods")) c.minperiods = parse_ll(*v, "minperiods");
    if (auto v = a.optional("maxperiods")) c.maxperiods = parse_ll(*v, "maxperiods");
    if (auto v = a.optional("minmob")) c.minmob = parse_ll(*v, "minmob");
    if (auto v = a.optional("maxmob")) c.maxmob = parse_ll(*v, "maxmob");
    if (auto v = a.optional("rate_movers")) {
        c.has_rate_movers = true;
        c.rate_movers = parse_double(*v, "rate_movers");
    }
    if (auto v = a.optional("rate_stayers")) {
        c.has_rate_stayers = true;
        c.rate_stayers = parse_double(*v, "rate_stayers");
    }
    if (auto v = a.optional("mobstrata")) c.mobstrata = parse_bool(*v, "mobstrata");
    if (auto v = a.optional("connectivity")) c.connectivity = parse_bool(*v, "connectivity");
    if (auto v = a.optional("reconnect")) c.reconnect = parse_bool(*v, "reconnect");
    if (auto v = a.optional("recon_rule")) c.recon_rule = parse_recon_rule(*v);
    if (auto v = a.optional("recon_target")) c.recon_target = parse_double(*v, "recon_target");
    if (auto v = a.optional("connected")) c.connected = parse_bool(*v, "connected");
    if (auto v = a.optional("num_threads")) c.num_threads = parse_int(*v, "num_threads");
    if (auto v = a.optional("verbose")) c.verbose = parse_bool(*v, "verbose");
    if (auto v = a.optional("s_prefix")) c.s_prefix = *v;
    if (c.s_prefix.empty()) c.s_prefix = "__xsf_";

    if ((c.balanced || c.minperiods >= 0 || c.maxperiods >= 0) && !c.has_time) {
        fail("balanced/minperiods()/maxperiods() require a time dimension");
    }
    if ((c.minmob >= 0 || c.maxmob >= 0 || c.has_rate_movers || c.has_rate_stayers || c.connected ||
         c.reconnect || c.mobstrata || c.connectivity) &&
        !c.has_mob) {
        fail("minmobility()/maxmobility()/movers()/stayers()/mobstrata/connectivity/connected/reconnect "
             "require a mobility dimension");
    }
    if (c.has_group && !c.has_unit) fail("group closure requires a sampling unit");
    if (c.reconnect && c.has_group) fail("reconnect may not be combined with a group() closure");
    for (double r : {c.rate_movers, c.rate_stayers}) {
        if (c.is_count) {
            if (r < 0.0 || std::floor(r) != r) fail("movers()/stayers() counts must be nonnegative integers");
        } else if (!(r >= 0.0 && r <= 100.0)) {
            fail("movers()/stayers() percentages must be between 0 and 100");
        }
    }
    return c;
}

// ---------------------------------------------------------------------------
// Helpers.
// ---------------------------------------------------------------------------
void save_scalar(const std::string& name, double value) {
    if (SF_scal_save(const_cast<char*>(name.c_str()), value)) {
        fail("failed to save scalar " + name);
    }
}

void display(const std::string& text) {
    std::string s = text;
    s.push_back('\n');
    SF_display(const_cast<char*>(s.c_str()));
}

class PhaseTimer {
public:
    explicit PhaseTimer(bool enabled) : enabled_(enabled), t0_(std::chrono::steady_clock::now()) {}
    void mark(const char* label) {
        if (!enabled_) return;
        const auto now = std::chrono::steady_clock::now();
        const double ms = std::chrono::duration<double, std::milli>(now - t0_).count();
        t0_ = now;
        char buf[160];
        std::snprintf(buf, sizeof(buf), "  xsamplefe phase %-28s %10.1f ms", label, ms);
        display(buf);
    }

private:
    bool enabled_;
    std::chrono::steady_clock::time_point t0_;
};

std::vector<int> selected_observations() {
    const int in1 = SF_in1();
    const int in2 = SF_in2();
    std::vector<int> obs;
    if (in2 < in1) return obs;
    obs.reserve(static_cast<std::size_t>(in2 - in1 + 1));
    for (int j = in1; j <= in2; ++j) {
        if (SF_ifobs(j)) obs.push_back(j);
    }
    return obs;
}

void read_column(int var, const std::vector<int>& obs, std::vector<double>& out) {
    const std::size_t n = obs.size();
    out.resize(n);
    for (std::size_t i = 0; i < n; ++i) {
        ST_double z = 0.0;
        if (SF_vdata(var, obs[i], &z)) {
            fail("failed to read variable " + std::to_string(var) + " (obs " + std::to_string(obs[i]) + ")");
        }
        out[i] = z;
    }
}

// Dense rank (0-based, ascending by value) of the rows where mask[i] != 0 and
// the value is not Stata-missing. Returns the number of distinct values; rows
// outside the mask (or missing) get id -1.
int64_t dense_rank_column(const std::vector<double>& v, const std::vector<uint8_t>* mask, double missval,
                          std::vector<int32_t>& id) {
    const std::size_t n = v.size();
    std::vector<int32_t> idx;
    idx.reserve(n);
    for (std::size_t i = 0; i < n; ++i) {
        if ((!mask || (*mask)[i]) && v[i] < missval) idx.push_back(static_cast<int32_t>(i));
    }
    XSF_PARALLEL_SORT(idx.begin(), idx.end(), [&](int32_t a, int32_t b) { return v[a] < v[b]; });
    id.assign(n, -1);
    int64_t next = -1;
    double prev = 0.0;
    for (std::size_t k = 0; k < idx.size(); ++k) {
        const double z = v[idx[k]];
        if (next < 0 || z != prev) {
            ++next;
            prev = z;
        }
        id[idx[k]] = static_cast<int32_t>(next);
    }
    return next + 1;
}

// Lexicographic dense rank of a tuple of columns (strata). Stata missing
// values are ordinary categories here (as in `sample, by()`, where rows with
// a missing by() value form their own group); they sort after every
// non-missing value because Stata encodes them as large doubles.
int64_t dense_rank_tuple(const std::vector<std::vector<double>>& cols, const std::vector<uint8_t>& mask,
                         std::vector<int32_t>& id) {
    const std::size_t n = mask.size();
    const std::size_t k = cols.size();
    std::vector<int32_t> idx;
    idx.reserve(n);
    for (std::size_t i = 0; i < n; ++i) {
        if (mask[i]) idx.push_back(static_cast<int32_t>(i));
    }
    auto less = [&](int32_t a, int32_t b) {
        for (std::size_t c = 0; c < k; ++c) {
            const double x = cols[c][a];
            const double y = cols[c][b];
            if (x != y) return x < y;
        }
        return false;
    };
    XSF_PARALLEL_SORT(idx.begin(), idx.end(), less);
    id.assign(n, -1);
    int64_t next = -1;
    for (std::size_t r = 0; r < idx.size(); ++r) {
        if (r == 0 || less(idx[r - 1], idx[r])) ++next;
        id[idx[r]] = static_cast<int32_t>(next);
    }
    return next + 1;
}

// Compressed row storage: rows grouped by id, in physical row order.
struct Csr {
    std::vector<int64_t> off;
    std::vector<int32_t> rows;
};

Csr build_csr(const std::vector<int32_t>& id, int64_t nid, const std::vector<uint8_t>* mask) {
    Csr csr;
    csr.off.assign(static_cast<std::size_t>(nid) + 1, 0);
    const std::size_t n = id.size();
    for (std::size_t i = 0; i < n; ++i) {
        if ((!mask || (*mask)[i]) && id[i] >= 0) ++csr.off[static_cast<std::size_t>(id[i]) + 1];
    }
    for (std::size_t g = 0; g < static_cast<std::size_t>(nid); ++g) csr.off[g + 1] += csr.off[g];
    csr.rows.resize(static_cast<std::size_t>(csr.off[static_cast<std::size_t>(nid)]));
    std::vector<int64_t> cur(csr.off.begin(), csr.off.end() - 1);
    for (std::size_t i = 0; i < n; ++i) {
        if ((!mask || (*mask)[i]) && id[i] >= 0) {
            csr.rows[static_cast<std::size_t>(cur[static_cast<std::size_t>(id[i])]++)] = static_cast<int32_t>(i);
        }
    }
    return csr;
}

// Number of distinct non-negative ids in buf (negative = Stata missing,
// which never counts as a period or a link).
int32_t count_distinct_sorted(std::vector<int32_t>& buf) {
    if (buf.empty()) return 0;
    std::sort(buf.begin(), buf.end());
    int32_t d = 0;
    for (std::size_t k = 0; k < buf.size(); ++k) {
        if (buf[k] < 0) continue;
        if (d == 0 || buf[k] != buf[k - 1]) ++d;
    }
    return d;
}

// Iterative union-find with path halving (deterministic, serial use).
struct UnionFind {
    std::vector<int32_t> parent;
    explicit UnionFind(int64_t n) : parent(static_cast<std::size_t>(n)) {
        for (std::size_t i = 0; i < parent.size(); ++i) parent[i] = static_cast<int32_t>(i);
    }
    int32_t find(int32_t x) {
        while (parent[static_cast<std::size_t>(x)] != x) {
            const int32_t gp = parent[static_cast<std::size_t>(parent[static_cast<std::size_t>(x)])];
            parent[static_cast<std::size_t>(x)] = gp;
            x = gp;
        }
        return x;
    }
    void unite(int32_t a, int32_t b) {
        a = find(a);
        b = find(b);
        if (a == b) return;
        // Attach the larger root id under the smaller one: keeps roots
        // canonical (smallest id) independently of insertion order.
        if (a < b) {
            parent[static_cast<std::size_t>(b)] = a;
        } else {
            parent[static_cast<std::size_t>(a)] = b;
        }
    }
};

// Stata's sample: keep int(N * pct / 100 + .5) observations per stratum. The
// count is saturated *before* the cast, so a count larger than the stratum (or
// larger than what long long can hold) keeps the stratum whole.
int64_t target_size(int64_t n, bool is_count, double pct, double count) {
    if (n <= 0) return 0;
    if (is_count) {
        if (!(count > 0.0)) return 0;
        if (count >= static_cast<double>(n)) return n;
        return static_cast<int64_t>(count);
    }
    const double k = std::floor(static_cast<double>(n) * pct / 100.0 + 0.5);
    return std::max<int64_t>(0, std::min<int64_t>(n, static_cast<int64_t>(k)));
}

// Row, unit, stratum and graph-node indices are int32_t; every count that will
// be cast to one is checked first so that a too-large dataset fails loudly.
constexpr int64_t kIndexLimit = static_cast<int64_t>(std::numeric_limits<int32_t>::max());

void check_index_space(int64_t v, const char* what) {
    if (v > kIndexLimit) {
        fail(std::string(what) + " (" + std::to_string(v) +
             ") exceeds the 2,147,483,647 limit of this plugin's 32-bit indices");
    }
}

inline uint64_t splitmix64(uint64_t x) {
    x += 0x9e3779b97f4a7c15ULL;
    x = (x ^ (x >> 30)) * 0xbf58476d1ce4e5b9ULL;
    x = (x ^ (x >> 27)) * 0x94d049bb133111ebULL;
    return x ^ (x >> 31);
}

inline uint64_t double_bits(double d) {
    uint64_t b = 0;
    std::memcpy(&b, &d, sizeof(b));
    return b;
}

}  // namespace

STDLL stata_call(int argc, char* argv[]) {
    try {
        ParsedArgs args(argc, argv);
        const Config cfg = parse_config(args);
        ScopedThreadRequest thread_request(cfg.num_threads);
        ThreadStats ts;
        PhaseTimer timer(cfg.verbose);

        // ---- varlist layout ------------------------------------------------
        const int expected_vars = 1 + (cfg.has_unit ? 1 : 0) + cfg.nby + (cfg.has_time ? 1 : 0) +
                                  (cfg.has_mob ? 1 : 0) + (cfg.has_group ? 1 : 0) + cfg.nu + 1;
        if (SF_nvars() != expected_vars) {
            fail("varlist has wrong length (have " + std::to_string(SF_nvars()) + ", want " +
                 std::to_string(expected_vars) + ")");
        }
        int cursor = 1;
        const int idx_touse = cursor++;
        const int idx_unit = cfg.has_unit ? cursor++ : -1;
        const int idx_by = cursor;
        cursor += cfg.nby;
        const int idx_time = cfg.has_time ? cursor++ : -1;
        const int idx_mob = cfg.has_mob ? cursor++ : -1;
        const int idx_group = cfg.has_group ? cursor++ : -1;
        const int idx_u = cursor;
        cursor += cfg.nu;
        const int idx_out = cursor;

        const std::vector<int> obs = selected_observations();
        const int64_t n = static_cast<int64_t>(obs.size());
        check_index_space(n, "the number of observations");
        const double missval = SV_missval;

        // ---- read columns ---------------------------------------------------
        std::vector<uint8_t> frame(static_cast<std::size_t>(n), 0);
        {
            std::vector<double> t;
            read_column(idx_touse, obs, t);
            for (int64_t i = 0; i < n; ++i) {
                frame[static_cast<std::size_t>(i)] = (t[static_cast<std::size_t>(i)] < missval &&
                                                      t[static_cast<std::size_t>(i)] != 0.0)
                                                         ? 1
                                                         : 0;
            }
        }
        std::vector<double> unit_raw, time_raw, mob_raw, group_raw;
        std::vector<std::vector<double>> by_raw(static_cast<std::size_t>(cfg.nby));
        std::vector<std::vector<double>> u_raw(static_cast<std::size_t>(cfg.nu));
        if (cfg.has_unit) read_column(idx_unit, obs, unit_raw);
        for (int c = 0; c < cfg.nby; ++c) read_column(idx_by + c, obs, by_raw[static_cast<std::size_t>(c)]);
        if (cfg.has_time) read_column(idx_time, obs, time_raw);
        if (cfg.has_mob) read_column(idx_mob, obs, mob_raw);
        if (cfg.has_group) read_column(idx_group, obs, group_raw);
        for (int c = 0; c < cfg.nu; ++c) read_column(idx_u + c, obs, u_raw[static_cast<std::size_t>(c)]);
        timer.mark("read");

        // ---- if/in frame rule on inseparable blocks -------------------------
        // The block is the group() variable when present, else the unit. A
        // block that has rows both inside and outside if/in is "split".
        int64_t n_split = 0;
        if (cfg.has_unit) {
            const std::vector<double>& block_raw = cfg.has_group ? group_raw : unit_raw;
            std::vector<int32_t> block_id;
            const int64_t nblock = dense_rank_column(block_raw, nullptr, missval, block_id);
            const Csr bcsr = build_csr(block_id, nblock, nullptr);
            std::vector<uint8_t> split(static_cast<std::size_t>(nblock), 0);
#pragma omp parallel
            {
                observe_team(ts);
#pragma omp for schedule(static)
                for (int64_t b = 0; b < nblock; ++b) {
                    const int64_t lo = bcsr.off[static_cast<std::size_t>(b)];
                    const int64_t hi = bcsr.off[static_cast<std::size_t>(b) + 1];
                    int64_t inside = 0;
                    for (int64_t k = lo; k < hi; ++k) inside += frame[static_cast<std::size_t>(bcsr.rows[static_cast<std::size_t>(k)])];
                    if (inside > 0 && inside < hi - lo) {
                        split[static_cast<std::size_t>(b)] = 1;
                        if (cfg.frame_rule == FrameRule::Any) {
                            for (int64_t k = lo; k < hi; ++k) frame[static_cast<std::size_t>(bcsr.rows[static_cast<std::size_t>(k)])] = 1;
                        } else if (cfg.frame_rule == FrameRule::All) {
                            for (int64_t k = lo; k < hi; ++k) frame[static_cast<std::size_t>(bcsr.rows[static_cast<std::size_t>(k)])] = 0;
                        }
                    }
                }
            }
            for (int64_t b = 0; b < nblock; ++b) n_split += split[static_cast<std::size_t>(b)];
            if (cfg.frame_rule == FrameRule::Strict && n_split > 0) {
                fail(std::to_string(n_split) + (cfg.has_group ? " group(s)" : " unit(s)") +
                     " have rows both inside and outside if/in; sampling units must be complete "
                     "(specify option any or all to resolve)");
            }
            timer.mark("frame rule");
        }

        int64_t n_frame = 0;
        for (int64_t i = 0; i < n; ++i) n_frame += frame[static_cast<std::size_t>(i)];

        // Rows pulled into the frame by `any` must carry every required key.
        if (n_frame > 0 && cfg.frame_rule == FrameRule::Any && n_split > 0) {
            int64_t bad = 0;
            for (int64_t i = 0; i < n; ++i) {
                if (!frame[static_cast<std::size_t>(i)]) continue;
                bool ok = true;
                if (cfg.has_unit && !(unit_raw[static_cast<std::size_t>(i)] < missval)) ok = false;
                if (ok && cfg.has_group && !(group_raw[static_cast<std::size_t>(i)] < missval)) ok = false;
                if (!ok) ++bad;
            }
            if (bad > 0) {
                fail(std::to_string(bad) + " row(s) pulled into the frame by option any have missing "
                     "unit()/group() values");
            }
        }

        // ---- ids over frame rows ------------------------------------------
        std::vector<int32_t> unit_id(static_cast<std::size_t>(n), -1);
        int64_t U = 0;
        if (n_frame > 0) {
            if (cfg.has_unit) {
                U = dense_rank_column(unit_raw, &frame, missval, unit_id);
            } else {
                // Observation-level sampling: every frame row is its own unit,
                // numbered in physical order (the row keeps its own uniforms).
                for (int64_t i = 0; i < n; ++i) {
                    if (frame[static_cast<std::size_t>(i)]) unit_id[static_cast<std::size_t>(i)] = static_cast<int32_t>(U++);
                }
            }
        }
        std::vector<int32_t> strata_id(static_cast<std::size_t>(n), -1);
        int64_t S = 1;
        if (cfg.nby > 0) {
            S = dense_rank_tuple(by_raw, frame, strata_id);
        } else {
            for (int64_t i = 0; i < n; ++i) {
                if (frame[static_cast<std::size_t>(i)]) strata_id[static_cast<std::size_t>(i)] = 0;
            }
        }
        std::vector<int32_t> time_id, mob_id, group_id;
        int64_t T = 0, M = 0, G = 0;
        if (cfg.has_time) T = dense_rank_column(time_raw, &frame, missval, time_id);
        if (cfg.has_mob) M = dense_rank_column(mob_raw, &frame, missval, mob_id);
        if (cfg.has_group) G = dense_rank_column(group_raw, &frame, missval, group_id);
        // the unit-mobility graph numbers units 0..U-1 and mobility values U..U+M-1
        if (cfg.has_mob) check_index_space(U + M, "the number of units plus mobility values");
        timer.mark("ids");

        // Row -> uniform key row: observation mode uses the row's own draws,
        // unit mode uses the r-th draw for the r-th smallest unit value.
        std::vector<int32_t> key_row(static_cast<std::size_t>(U), 0);
        if (cfg.has_unit) {
            for (int64_t u = 0; u < U; ++u) key_row[static_cast<std::size_t>(u)] = static_cast<int32_t>(u);
        } else {
            for (int64_t i = 0; i < n; ++i) {
                const int32_t u = unit_id[static_cast<std::size_t>(i)];
                if (u >= 0) key_row[static_cast<std::size_t>(u)] = static_cast<int32_t>(i);
            }
        }

        // ---- per-unit aggregates ------------------------------------------
        const Csr ucsr = build_csr(unit_id, U, &frame);
        std::vector<int64_t> u_nobs(static_cast<std::size_t>(U), 0);
        std::vector<int32_t> u_nper(static_cast<std::size_t>(U), 0);
        std::vector<int32_t> u_nmob(static_cast<std::size_t>(U), 0);
        std::vector<int32_t> u_str(static_cast<std::size_t>(U), 0);
        std::vector<uint8_t> u_conf(static_cast<std::size_t>(U), 0);
#pragma omp parallel
        {
            observe_team(ts);
            std::vector<int32_t> buf;
#pragma omp for schedule(dynamic, 256)
            for (int64_t u = 0; u < U; ++u) {
                const int64_t lo = ucsr.off[static_cast<std::size_t>(u)];
                const int64_t hi = ucsr.off[static_cast<std::size_t>(u) + 1];
                u_nobs[static_cast<std::size_t>(u)] = hi - lo;
                if (hi <= lo) continue;
                const int32_t s0 = strata_id[static_cast<std::size_t>(ucsr.rows[static_cast<std::size_t>(lo)])];
                u_str[static_cast<std::size_t>(u)] = s0;
                for (int64_t k = lo + 1; k < hi; ++k) {
                    if (strata_id[static_cast<std::size_t>(ucsr.rows[static_cast<std::size_t>(k)])] != s0) {
                        u_conf[static_cast<std::size_t>(u)] = 1;
                        break;
                    }
                }
                if (cfg.has_time) {
                    buf.resize(static_cast<std::size_t>(hi - lo));
                    for (int64_t k = lo; k < hi; ++k) buf[static_cast<std::size_t>(k - lo)] = time_id[static_cast<std::size_t>(ucsr.rows[static_cast<std::size_t>(k)])];
                    u_nper[static_cast<std::size_t>(u)] = count_distinct_sorted(buf);
                }
                if (cfg.has_mob) {
                    buf.resize(static_cast<std::size_t>(hi - lo));
                    for (int64_t k = lo; k < hi; ++k) buf[static_cast<std::size_t>(k - lo)] = mob_id[static_cast<std::size_t>(ucsr.rows[static_cast<std::size_t>(k)])];
                    u_nmob[static_cast<std::size_t>(u)] = count_distinct_sorted(buf);
                }
            }
        }
        {
            int64_t nconf = 0;
            for (int64_t u = 0; u < U; ++u) nconf += u_conf[static_cast<std::size_t>(u)];
            if (nconf > 0) {
                fail("by() variables must be constant within sampling units (" + std::to_string(nconf) +
                     " unit(s) violate this)");
            }
        }
        timer.mark("unit aggregates");

        // ---- mobstrata: the mobility class of the unit joins the by() strata --
        const int64_t S_by_report = (cfg.nby > 0 ? S : 1);
        if (cfg.mobstrata && U > 0) {
            std::vector<int32_t> ord(static_cast<std::size_t>(U));
            for (int64_t u = 0; u < U; ++u) ord[static_cast<std::size_t>(u)] = static_cast<int32_t>(u);
            auto less = [&](int32_t a, int32_t b) {
                const std::size_t aa = static_cast<std::size_t>(a);
                const std::size_t bb = static_cast<std::size_t>(b);
                if (u_str[aa] != u_str[bb]) return u_str[aa] < u_str[bb];
                return u_nmob[aa] < u_nmob[bb];
            };
            std::sort(ord.begin(), ord.end(), less);
            std::vector<int32_t> ns(static_cast<std::size_t>(U), 0);
            int64_t next = -1;
            for (std::size_t k = 0; k < ord.size(); ++k) {
                if (k == 0 || less(ord[k - 1], ord[k])) ++next;
                ns[static_cast<std::size_t>(ord[k])] = static_cast<int32_t>(next);
            }
            u_str.swap(ns);
            S = next + 1;
        }

        // ---- eligibility and final strata -----------------------------------
        const bool has_rates = cfg.has_rate_movers || cfg.has_rate_stayers;
        check_index_space(has_rates ? 2 * S : S, "the number of strata");
        const int64_t SF = has_rates ? 2 * S : S;
        std::vector<uint8_t> u_elig(static_cast<std::size_t>(U), 0);
        std::vector<int32_t> u_fs(static_cast<std::size_t>(U), -1);
#pragma omp parallel
        {
            observe_team(ts);
#pragma omp for schedule(static)
            for (int64_t u = 0; u < U; ++u) {
                const std::size_t uu = static_cast<std::size_t>(u);
                if (u_nobs[uu] <= 0) continue;
                bool ok = true;
                if (cfg.minobs >= 0 && u_nobs[uu] < cfg.minobs) ok = false;
                if (cfg.maxobs >= 0 && u_nobs[uu] > cfg.maxobs) ok = false;
                if (cfg.has_time) {
                    if (cfg.minperiods >= 0 && u_nper[uu] < cfg.minperiods) ok = false;
                    if (cfg.maxperiods >= 0 && u_nper[uu] > cfg.maxperiods) ok = false;
                    // balanced needs full coverage *and* at least one valid
                    // period: with no non-missing time() no unit is eligible
                    if (cfg.balanced && (u_nper[uu] == 0 || u_nper[uu] != T)) ok = false;
                }
                if (cfg.has_mob) {
                    if (cfg.minmob >= 0 && u_nmob[uu] < cfg.minmob) ok = false;
                    if (cfg.maxmob >= 0 && u_nmob[uu] > cfg.maxmob) ok = false;
                }
                if (!ok) continue;
                u_elig[uu] = 1;
                const int32_t mover = (cfg.has_mob && u_nmob[uu] >= 2) ? 1 : 0;
                u_fs[uu] = has_rates ? (u_str[uu] * 2 + mover) : u_str[uu];
            }
        }

        std::vector<int64_t> fs_n(static_cast<std::size_t>(SF), 0);
        int64_t U_elig = 0, U_movers_elig = 0, N_inelig = 0, U_inelig = 0;
        for (int64_t u = 0; u < U; ++u) {
            const std::size_t uu = static_cast<std::size_t>(u);
            if (u_nobs[uu] <= 0) continue;
            if (u_elig[uu]) {
                ++U_elig;
                ++fs_n[static_cast<std::size_t>(u_fs[uu])];
                if (cfg.has_mob && u_nmob[uu] >= 2) ++U_movers_elig;
            } else {
                ++U_inelig;
                N_inelig += u_nobs[uu];
            }
        }
        std::vector<int64_t> fs_k(static_cast<std::size_t>(SF), 0);
        int64_t K_total = 0;
        int64_t S_nonempty = 0;
        for (int64_t s = 0; s < SF; ++s) {
            const std::size_t ss = static_cast<std::size_t>(s);
            if (fs_n[ss] == 0) continue;
            ++S_nonempty;
            bool is_count = cfg.is_count;
            double pct = cfg.pct;
            double count = static_cast<double>(cfg.count);
            if (has_rates) {
                const bool mover_class = (s % 2 == 1);
                if (mover_class && cfg.has_rate_movers) {
                    if (is_count) count = cfg.rate_movers;
                    else pct = cfg.rate_movers;
                } else if (!mover_class && cfg.has_rate_stayers) {
                    if (is_count) count = cfg.rate_stayers;
                    else pct = cfg.rate_stayers;
                }
            }
            fs_k[ss] = target_size(fs_n[ss], is_count, pct, count);
            K_total += fs_k[ss];
        }
        timer.mark("eligibility");

        // ---- connectivity of the bipartite unit x mobility graph ------------
        // Groups are indivisible, so their units belong to the same component.
        struct CompStats {
            int64_t ncomp = 0, rows = 0, units = 0, mobs = 0;
            int64_t lcc_rows = 0, lcc_units = 0, lcc_mobs = 0;
            int32_t lcc_root = -1;
        };
        // One pass over the rows builds the graph and the per-unit row counts;
        // everything else is aggregated over units and mobility values.
        std::vector<int64_t> g_urows, g_crows;
        std::vector<int32_t> g_uroot;
        std::vector<uint8_t> g_mseen;
        auto analyse_graph = [&](const std::vector<uint8_t>& rowmask, UnionFind& uf,
                                 std::vector<uint8_t>* lcc_unit_flag) {
            g_urows.assign(static_cast<std::size_t>(U), 0);
            g_crows.assign(static_cast<std::size_t>(U + M), 0);
            g_mseen.assign(static_cast<std::size_t>(M), 0);
            std::vector<int32_t> gfirst;
            if (cfg.has_group) gfirst.assign(static_cast<std::size_t>(G), -1);
            for (int64_t i = 0; i < n; ++i) {
                const std::size_t ii = static_cast<std::size_t>(i);
                if (!rowmask[ii]) continue;
                const int32_t u = unit_id[ii];
                ++g_urows[static_cast<std::size_t>(u)];
                if (mob_id[ii] >= 0) {
                    g_mseen[static_cast<std::size_t>(mob_id[ii])] = 1;
                    uf.unite(u, static_cast<int32_t>(U + mob_id[ii]));
                }
                if (cfg.has_group && group_id[ii] >= 0) {
                    int32_t& f = gfirst[static_cast<std::size_t>(group_id[ii])];
                    if (f < 0) f = u;
                    else uf.unite(u, f);
                }
            }
            CompStats cs;
            g_uroot.assign(static_cast<std::size_t>(U), -1);
            for (int64_t u = 0; u < U; ++u) {
                const std::size_t uu = static_cast<std::size_t>(u);
                const int64_t rows = g_urows[uu];
                if (rows <= 0) continue;
                ++cs.units;
                cs.rows += rows;
                const int32_t r = uf.find(static_cast<int32_t>(u));
                g_uroot[uu] = r;
                g_crows[static_cast<std::size_t>(r)] += rows;
                // roots are canonical (the smallest node id of the component)
                // and every component with rows contains a unit
                if (r == static_cast<int32_t>(u)) ++cs.ncomp;
            }
            for (int64_t u = 0; u < U; ++u) {
                const int32_t r = g_uroot[static_cast<std::size_t>(u)];
                if (r < 0) continue;
                const int64_t rows = g_crows[static_cast<std::size_t>(r)];
                if (rows > cs.lcc_rows) {  // ties: the smallest unit id wins
                    cs.lcc_rows = rows;
                    cs.lcc_root = r;
                }
            }
            for (int64_t m = 0; m < M; ++m) if (g_mseen[static_cast<std::size_t>(m)]) ++cs.mobs;
            if (lcc_unit_flag) lcc_unit_flag->assign(static_cast<std::size_t>(U), 0);
            if (cs.lcc_root >= 0) {
                for (int64_t u = 0; u < U; ++u) {
                    const std::size_t uu = static_cast<std::size_t>(u);
                    if (g_uroot[uu] != cs.lcc_root) continue;
                    ++cs.lcc_units;
                    if (lcc_unit_flag) (*lcc_unit_flag)[uu] = 1;
                }
                for (int64_t m = 0; m < M; ++m) {
                    if (!g_mseen[static_cast<std::size_t>(m)]) continue;
                    if (uf.find(static_cast<int32_t>(U + m)) == cs.lcc_root) ++cs.lcc_mobs;
                }
            }
            return cs;
        };

        // the graph passes cost a full union-find over the rows, so they run
        // only when their result is asked for
        const bool diag = cfg.connectivity || cfg.reconnect || cfg.connected;
        CompStats frame_cs;
        std::vector<uint8_t> u_lcc_frame;
        if (diag && cfg.has_mob && n_frame > 0) {
            std::vector<uint8_t> rowmask(static_cast<std::size_t>(n), 0);
            for (int64_t i = 0; i < n; ++i) {
                const std::size_t ii = static_cast<std::size_t>(i);
                rowmask[ii] = (frame[ii] && u_elig[static_cast<std::size_t>(unit_id[ii])]) ? 1 : 0;
            }
            UnionFind uf(U + M);
            frame_cs = analyse_graph(rowmask, uf, &u_lcc_frame);
            timer.mark("frame connectivity");
        }

        // ---- selection: k_g smallest keys inside every final stratum --------
        const Csr fcsr = build_csr(u_fs, SF, &u_elig);
        std::vector<int32_t> fs_units = fcsr.rows;  // mutable copy for nth_element
        std::vector<uint8_t> u_sel(static_cast<std::size_t>(U), 0);
        bool need_keys = false;
        for (int64_t s = 0; s < SF; ++s) {
            const std::size_t ss = static_cast<std::size_t>(s);
            if (fs_k[ss] > 0 && fs_k[ss] < fs_n[ss]) need_keys = true;
        }
        if (need_keys && cfg.nu <= 0) fail("internal error: uniform keys required but none were supplied");
        // Unit mode: the second and further uniform columns start at draw _N+1,
        // so using them to break a tie in the first key would make the draw
        // depend on the number of rows. The tie is broken instead by a hash of
        // the first key and of the unit's rank, which depends only on the seed
        // and on the set of unit values (see Reproducibility in the help).
        std::vector<uint64_t> u_tie;
        if (cfg.has_unit && cfg.nu > 0 && U > 0) {
            u_tie.resize(static_cast<std::size_t>(U));
            for (int64_t u = 0; u < U; ++u) {
                const std::size_t uu = static_cast<std::size_t>(u);
                u_tie[uu] = splitmix64(double_bits(u_raw[0][uu]) ^ splitmix64(static_cast<uint64_t>(u)));
            }
        }
        auto key_less = [&](int32_t a, int32_t b) {
            const std::size_t ra = static_cast<std::size_t>(key_row[static_cast<std::size_t>(a)]);
            const std::size_t rb = static_cast<std::size_t>(key_row[static_cast<std::size_t>(b)]);
            if (cfg.has_unit) {
                const double x = u_raw[0][ra];
                const double y = u_raw[0][rb];
                if (x != y) return x < y;
                const uint64_t ha = u_tie[static_cast<std::size_t>(a)];
                const uint64_t hb = u_tie[static_cast<std::size_t>(b)];
                if (ha != hb) return ha < hb;
                return a < b;
            }
            for (int c = 0; c < cfg.nu; ++c) {
                const double x = u_raw[static_cast<std::size_t>(c)][ra];
                const double y = u_raw[static_cast<std::size_t>(c)][rb];
                if (x != y) return x < y;
            }
            return a < b;
        };
#pragma omp parallel
        {
            observe_team(ts);
#pragma omp for schedule(dynamic, 1)
            for (int64_t s = 0; s < SF; ++s) {
                const std::size_t ss = static_cast<std::size_t>(s);
                const int64_t lo = fcsr.off[ss];
                const int64_t hi = fcsr.off[ss + 1];
                const int64_t k = fs_k[ss];
                if (k <= 0 || hi <= lo) continue;
                auto first = fs_units.begin() + static_cast<std::ptrdiff_t>(lo);
                auto last = fs_units.begin() + static_cast<std::ptrdiff_t>(hi);
                if (k < hi - lo) {
                    std::nth_element(first, first + static_cast<std::ptrdiff_t>(k - 1), last, key_less);
                }
                for (int64_t j = 0; j < k; ++j) u_sel[static_cast<std::size_t>(*(first + static_cast<std::ptrdiff_t>(j)))] = 1;
            }
        }
        int64_t U_sel = 0, U_movers_sel = 0;
        for (int64_t u = 0; u < U; ++u) {
            const std::size_t uu = static_cast<std::size_t>(u);
            if (!u_sel[uu]) continue;
            ++U_sel;
            if (cfg.has_mob && u_nmob[uu] >= 2) ++U_movers_sel;
        }
        timer.mark("selection");

        // ---- row retention, group closure, connected set --------------------
        std::vector<uint8_t> keep(static_cast<std::size_t>(n), 1);  // rows outside if/in are kept
#pragma omp parallel
        {
            observe_team(ts);
#pragma omp for schedule(static)
            for (int64_t i = 0; i < n; ++i) {
                const std::size_t ii = static_cast<std::size_t>(i);
                if (frame[ii]) keep[ii] = u_sel[static_cast<std::size_t>(unit_id[ii])];
            }
        }
        int64_t G_kept = 0;
        if (cfg.has_group && n_frame > 0) {
            const Csr gcsr = build_csr(group_id, G, &frame);
            std::vector<uint8_t> gkeep(static_cast<std::size_t>(G), 0);
#pragma omp parallel
            {
                observe_team(ts);
#pragma omp for schedule(dynamic, 256)
                for (int64_t g = 0; g < G; ++g) {
                    const std::size_t gg = static_cast<std::size_t>(g);
                    const int64_t lo = gcsr.off[gg];
                    const int64_t hi = gcsr.off[gg + 1];
                    if (hi <= lo) continue;
                    int64_t kept = 0;
                    for (int64_t k = lo; k < hi; ++k) kept += keep[static_cast<std::size_t>(gcsr.rows[static_cast<std::size_t>(k)])];
                    gkeep[gg] = (cfg.group_rule == GroupRule::Any) ? (kept > 0) : (kept == hi - lo);
                }
            }
            for (int64_t g = 0; g < G; ++g) G_kept += gkeep[static_cast<std::size_t>(g)];
#pragma omp parallel
            {
                observe_team(ts);
#pragma omp for schedule(static)
                for (int64_t i = 0; i < n; ++i) {
                    const std::size_t ii = static_cast<std::size_t>(i);
                    if (frame[ii]) keep[ii] = gkeep[static_cast<std::size_t>(group_id[ii])];
                }
            }
            timer.mark("group closure");
        }

        // ---- reconnect: grow the sample's largest component to the target ----
        int64_t U_reconnected = 0, N_reconnected = 0;
        if (cfg.reconnect && n_frame > 0 && U > 0) {
            std::vector<uint8_t> rowmask(static_cast<std::size_t>(n), 0);
            for (int64_t i = 0; i < n; ++i) {
                const std::size_t ii = static_cast<std::size_t>(i);
                rowmask[ii] = (frame[ii] && keep[ii]) ? 1 : 0;
            }
            UnionFind uf(U + M);
            const CompStats cs0 = analyse_graph(rowmask, uf, nullptr);
            std::vector<int64_t> crows;
            crows.swap(g_crows);
            std::vector<int64_t> urows;
            urows.swap(g_urows);
            int64_t total = cs0.rows;
            int32_t lcc = cs0.lcc_root;
            int64_t best = cs0.lcc_rows;
            const double target =
                (cfg.recon_target >= 0.0)
                    ? cfg.recon_target / 100.0
                    : (frame_cs.rows > 0 ? static_cast<double>(frame_cs.lcc_rows) /
                                               static_cast<double>(frame_cs.rows)
                                         : 0.0);
            std::vector<uint8_t> cand(static_cast<std::size_t>(U), 0);
            int64_t ncand = 0;
            for (int64_t u = 0; u < U; ++u) {
                const std::size_t uu = static_cast<std::size_t>(u);
                if (u_elig[uu] && urows[uu] <= 0) {
                    cand[uu] = 1;
                    ++ncand;
                }
            }
            if (lcc >= 0 && ncand > 0 && target > 0.0) {
                // distinct (mobility value, candidate unit) links, both ways
                std::vector<std::pair<int32_t, int32_t>> mu;
                for (int64_t i = 0; i < n; ++i) {
                    const std::size_t ii = static_cast<std::size_t>(i);
                    if (!frame[ii] || mob_id[ii] < 0) continue;
                    if (!cand[static_cast<std::size_t>(unit_id[ii])]) continue;
                    mu.emplace_back(mob_id[ii], unit_id[ii]);
                }
                std::sort(mu.begin(), mu.end());
                mu.erase(std::unique(mu.begin(), mu.end()), mu.end());
                std::vector<int64_t> moff(static_cast<std::size_t>(M) + 1, 0);
                for (const auto& e : mu) ++moff[static_cast<std::size_t>(e.first) + 1];
                for (int64_t m = 0; m < M; ++m) moff[static_cast<std::size_t>(m) + 1] += moff[static_cast<std::size_t>(m)];
                std::vector<std::pair<int32_t, int32_t>> um(mu.size());
                for (std::size_t k = 0; k < mu.size(); ++k) um[k] = {mu[k].second, mu[k].first};
                std::sort(um.begin(), um.end());
                std::vector<int64_t> uoff(static_cast<std::size_t>(U) + 1, 0);
                for (const auto& e : um) ++uoff[static_cast<std::size_t>(e.first) + 1];
                for (int64_t u = 0; u < U; ++u) uoff[static_cast<std::size_t>(u) + 1] += uoff[static_cast<std::size_t>(u)];

                auto unit_key_less = [&](int32_t a, int32_t b) {
                    if (!u_tie.empty()) {
                        const double x = u_raw[0][static_cast<std::size_t>(a)];
                        const double y = u_raw[0][static_cast<std::size_t>(b)];
                        if (x != y) return x < y;
                        const uint64_t ha = u_tie[static_cast<std::size_t>(a)];
                        const uint64_t hb = u_tie[static_cast<std::size_t>(b)];
                        if (ha != hb) return ha < hb;
                    }
                    return a < b;
                };
                std::vector<uint8_t> in_front(static_cast<std::size_t>(U), 0);
                std::vector<int32_t> front;
                auto push_mob = [&](int64_t m) {
                    for (int64_t k = moff[static_cast<std::size_t>(m)]; k < moff[static_cast<std::size_t>(m) + 1]; ++k) {
                        const int32_t u = mu[static_cast<std::size_t>(k)].second;
                        const std::size_t uu = static_cast<std::size_t>(u);
                        if (cand[uu] && !in_front[uu]) {
                            in_front[uu] = 1;
                            front.push_back(u);
                        }
                    }
                };
                auto rebuild_front = [&]() {
                    front.clear();
                    std::fill(in_front.begin(), in_front.end(), 0);
                    for (int64_t m = 0; m < M; ++m) {
                        if (uf.find(static_cast<int32_t>(U + m)) == lcc) push_mob(m);
                    }
                };
                std::vector<int32_t> roots;
                auto roots_of = [&](int32_t u, bool& touches) {
                    touches = false;
                    roots.clear();
                    for (int64_t k = uoff[static_cast<std::size_t>(u)]; k < uoff[static_cast<std::size_t>(u) + 1]; ++k) {
                        const int32_t r = uf.find(static_cast<int32_t>(U + um[static_cast<std::size_t>(k)].second));
                        if (r == lcc) touches = true;
                        else roots.push_back(r);
                    }
                    std::sort(roots.begin(), roots.end());
                    roots.erase(std::unique(roots.begin(), roots.end()), roots.end());
                };
                // Deterministic greedy over the frontier units that touch the
                // largest component: recon_rule=gain takes the one that joins
                // the most rows (ties by the unit's own key), recon_rule=key
                // takes the smallest key, i.e. a random order of the frontier.
                auto scan = [&]() {
                    int32_t pick = -1;
                    int64_t pick_gain = -1;
                    for (std::size_t f = 0; f < front.size(); ++f) {
                        const int32_t u = front[f];
                        if (!cand[static_cast<std::size_t>(u)]) continue;
                        bool touches = false;
                        roots_of(u, touches);
                        if (!touches) continue;
                        if (cfg.recon_rule == ReconRule::Key) {
                            if (pick < 0 || unit_key_less(u, pick)) pick = u;
                            continue;
                        }
                        int64_t gain = u_nobs[static_cast<std::size_t>(u)];
                        for (int32_t r : roots) gain += crows[static_cast<std::size_t>(r)];
                        if (gain > pick_gain || (gain == pick_gain && pick >= 0 && unit_key_less(u, pick))) {
                            pick_gain = gain;
                            pick = u;
                        }
                    }
                    return pick;
                };
                rebuild_front();
                bool refreshed = true;
                while (total > 0 && static_cast<double>(best) < target * static_cast<double>(total)) {
                    int32_t pick = scan();
                    if (pick < 0) {
                        if (refreshed) break;
                        rebuild_front();
                        refreshed = true;
                        pick = scan();
                        if (pick < 0) break;
                    }
                    const std::size_t pp = static_cast<std::size_t>(pick);
                    bool touches = false;
                    roots_of(pick, touches);
                    int64_t sum = crows[static_cast<std::size_t>(lcc)] + u_nobs[pp];
                    crows[static_cast<std::size_t>(lcc)] = 0;
                    for (int32_t r : roots) {
                        sum += crows[static_cast<std::size_t>(r)];
                        crows[static_cast<std::size_t>(r)] = 0;
                    }
                    const int64_t lo = ucsr.off[pp];
                    const int64_t hi = ucsr.off[pp + 1];
                    for (int64_t k = lo; k < hi; ++k) {
                        const int32_t row = ucsr.rows[static_cast<std::size_t>(k)];
                        keep[static_cast<std::size_t>(row)] = 1;
                        rowmask[static_cast<std::size_t>(row)] = 1;
                    }
                    for (int64_t k = uoff[pp]; k < uoff[pp + 1]; ++k) {
                        uf.unite(pick, static_cast<int32_t>(U + um[static_cast<std::size_t>(k)].second));
                    }
                    lcc = uf.find(pick);
                    crows[static_cast<std::size_t>(lcc)] = sum;
                    best = sum;
                    total += u_nobs[pp];
                    cand[pp] = 0;
                    urows[pp] = u_nobs[pp];
                    ++U_reconnected;
                    N_reconnected += u_nobs[pp];
                    for (int64_t k = uoff[pp]; k < uoff[pp + 1]; ++k) push_mob(um[static_cast<std::size_t>(k)].second);
                    refreshed = false;
                }
            }
            timer.mark("reconnect");
        }

        int64_t N_connected_dropped = 0;
        int64_t n_components = 0;
        if (cfg.connected && n_frame > 0) {
            std::vector<uint8_t> rowmask(static_cast<std::size_t>(n), 0);
            for (int64_t i = 0; i < n; ++i) {
                const std::size_t ii = static_cast<std::size_t>(i);
                rowmask[ii] = (frame[ii] && keep[ii]) ? 1 : 0;
            }
            UnionFind uf(U + M);
            const CompStats cs = analyse_graph(rowmask, uf, nullptr);
            n_components = cs.ncomp;
            for (int64_t i = 0; i < n; ++i) {
                const std::size_t ii = static_cast<std::size_t>(i);
                if (!rowmask[ii]) continue;
                if (uf.find(unit_id[ii]) != cs.lcc_root) {
                    keep[ii] = 0;
                    ++N_connected_dropped;
                }
            }
            timer.mark("connected set");
        }

        CompStats sample_cs;
        int64_t U_lcc_kept = 0;
        if (diag && cfg.has_mob && n_frame > 0) {
            std::vector<uint8_t> rowmask(static_cast<std::size_t>(n), 0);
            for (int64_t i = 0; i < n; ++i) {
                const std::size_t ii = static_cast<std::size_t>(i);
                rowmask[ii] = (frame[ii] && keep[ii]) ? 1 : 0;
            }
            UnionFind uf(U + M);
            std::vector<uint8_t> u_lcc_sample;
            sample_cs = analyse_graph(rowmask, uf, &u_lcc_sample);
            for (int64_t u = 0; u < U; ++u) {
                const std::size_t uu = static_cast<std::size_t>(u);
                if (u_lcc_sample[uu] && !u_lcc_frame.empty() && u_lcc_frame[uu]) ++U_lcc_kept;
            }
            timer.mark("sample connectivity");
        }

        // ---- retained-sample bookkeeping ------------------------------------
        int64_t N_frame_retained = 0;
        std::vector<int64_t> u_retrows(static_cast<std::size_t>(U), 0);
        std::vector<uint8_t> m_ret(static_cast<std::size_t>(M), 0);
        std::vector<uint8_t> g_ret(static_cast<std::size_t>(G), 0);
        for (int64_t i = 0; i < n; ++i) {
            const std::size_t ii = static_cast<std::size_t>(i);
            if (!frame[ii] || !keep[ii]) continue;
            ++N_frame_retained;
            ++u_retrows[static_cast<std::size_t>(unit_id[ii])];
            if (cfg.has_mob && mob_id[ii] >= 0) m_ret[static_cast<std::size_t>(mob_id[ii])] = 1;
            if (cfg.has_group) g_ret[static_cast<std::size_t>(group_id[ii])] = 1;
        }
        int64_t U_ret = 0, U_ret_movers = 0, M_ret = 0, G_ret = 0;
        int64_t U_partial = 0, U_inelig_ret = 0;
        for (int64_t u = 0; u < U; ++u) {
            const std::size_t uu = static_cast<std::size_t>(u);
            if (u_retrows[uu] <= 0) continue;
            ++U_ret;
            if (cfg.has_mob && u_nmob[uu] >= 2) ++U_ret_movers;
            // group closure can retain part of a unit, or bring back a unit
            // that the eligibility filters had dropped
            if (u_retrows[uu] < u_nobs[uu]) ++U_partial;
            if (!u_elig[uu]) ++U_inelig_ret;
        }
        for (int64_t m = 0; m < M; ++m) M_ret += m_ret[static_cast<std::size_t>(m)];
        for (int64_t g = 0; g < G; ++g) G_ret += g_ret[static_cast<std::size_t>(g)];

        // ---- write output ---------------------------------------------------
        for (int64_t i = 0; i < n; ++i) {
            const std::size_t ii = static_cast<std::size_t>(i);
            if (SF_vstore(idx_out, obs[ii], keep[ii] ? 1.0 : 0.0)) {
                fail("failed to store the sample indicator");
            }
        }
        timer.mark("write");

        const std::string p = cfg.s_prefix;
        save_scalar(p + "N_total", static_cast<double>(n));
        save_scalar(p + "N_frame", static_cast<double>(n_frame));
        save_scalar(p + "N_outside", static_cast<double>(n - n_frame));
        save_scalar(p + "N_ineligible", static_cast<double>(N_inelig));
        save_scalar(p + "N_frame_retained", static_cast<double>(N_frame_retained));
        save_scalar(p + "N_retained", static_cast<double>(N_frame_retained + (n - n_frame)));
        save_scalar(p + "N_connected_dropped", static_cast<double>(N_connected_dropped));
        save_scalar(p + "n_components", static_cast<double>(n_components));
        save_scalar(p + "U_frame", static_cast<double>(U));
        save_scalar(p + "U_eligible", static_cast<double>(U_elig));
        save_scalar(p + "U_ineligible", static_cast<double>(U_inelig));
        save_scalar(p + "U_selected", static_cast<double>(U_sel));
        save_scalar(p + "U_retained", static_cast<double>(U_ret));
        save_scalar(p + "U_movers_eligible", static_cast<double>(U_movers_elig));
        save_scalar(p + "U_movers_selected", static_cast<double>(U_movers_sel));
        save_scalar(p + "U_movers_retained", static_cast<double>(U_ret_movers));
        save_scalar(p + "U_split", static_cast<double>(n_split));
        save_scalar(p + "U_partial", static_cast<double>(U_partial));
        save_scalar(p + "U_inelig_ret", static_cast<double>(U_inelig_ret));
        save_scalar(p + "K_target", static_cast<double>(K_total));
        save_scalar(p + "S_by", static_cast<double>(S_by_report));
        save_scalar(p + "S_final", static_cast<double>(S_nonempty));
        save_scalar(p + "T_periods", cfg.has_time ? static_cast<double>(T) : SV_missval);
        save_scalar(p + "M_frame", cfg.has_mob ? static_cast<double>(M) : SV_missval);
        save_scalar(p + "M_retained", cfg.has_mob ? static_cast<double>(M_ret) : SV_missval);
        save_scalar(p + "G_frame", cfg.has_group ? static_cast<double>(G) : SV_missval);
        save_scalar(p + "G_kept", cfg.has_group ? static_cast<double>(G_kept) : SV_missval);
        save_scalar(p + "G_retained", cfg.has_group ? static_cast<double>(G_ret) : SV_missval);
        const double share_frame = frame_cs.rows > 0
                                       ? static_cast<double>(frame_cs.lcc_rows) / static_cast<double>(frame_cs.rows)
                                       : 0.0;
        const double share_sample = sample_cs.rows > 0
                                        ? static_cast<double>(sample_cs.lcc_rows) / static_cast<double>(sample_cs.rows)
                                        : 0.0;
        const double share_units = sample_cs.units > 0
                                       ? static_cast<double>(sample_cs.lcc_units) / static_cast<double>(sample_cs.units)
                                       : 0.0;
        const double share_mobs = sample_cs.mobs > 0
                                      ? static_cast<double>(sample_cs.lcc_mobs) / static_cast<double>(sample_cs.mobs)
                                      : 0.0;
        const bool has_diag = diag && cfg.has_mob;
        save_scalar(p + "C_frame", has_diag ? static_cast<double>(frame_cs.ncomp) : SV_missval);
        save_scalar(p + "LCC_frame_share", has_diag ? share_frame : SV_missval);
        save_scalar(p + "C_sample", has_diag ? static_cast<double>(sample_cs.ncomp) : SV_missval);
        save_scalar(p + "LCC_share", has_diag ? share_sample : SV_missval);
        save_scalar(p + "LCC_units_share", has_diag ? share_units : SV_missval);
        save_scalar(p + "LCC_mob_share", has_diag ? share_mobs : SV_missval);
        save_scalar(p + "U_lcc_kept", has_diag ? static_cast<double>(U_lcc_kept) : SV_missval);
        save_scalar(p + "U_reconnected", cfg.reconnect ? static_cast<double>(U_reconnected) : SV_missval);
        save_scalar(p + "N_reconnected", cfg.reconnect ? static_cast<double>(N_reconnected) : SV_missval);
        save_scalar(p + "threads_requested", static_cast<double>(cfg.num_threads));
        save_scalar(p + "threads_effective", static_cast<double>(effective_threads()));
        save_scalar(p + "threads_used", static_cast<double>(ts.max_team));
#ifdef _OPENMP
        save_scalar(p + "openmp_enabled", 1.0);
        save_scalar(p + "thread_capacity",
                    static_cast<double>(std::max(1, std::min(omp_get_num_procs(), omp_get_thread_limit()))));
#else
        save_scalar(p + "openmp_enabled", 0.0);
        save_scalar(p + "thread_capacity", 1.0);
#endif
        return static_cast<ST_retcode>(0);
    } catch (const std::exception& e) {
        std::string msg = e.what();
        if (msg.empty() || msg.back() != '\n') msg.push_back('\n');
        SF_error(const_cast<char*>(msg.c_str()));
        return static_cast<ST_retcode>(198);
    } catch (...) {
        const char* msg = "xsamplefe plugin: unknown error\n";
        SF_error(const_cast<char*>(msg));
        return static_cast<ST_retcode>(198);
    }
}
